server:
  port: 8083
simplerpc:
  netty:
    server:
      port: 9092
      #  设置日志打印级别
      loglevel: debug
      threadpoll:
        #    连接处理线程数
        bossGroupSize: 1
        #    读写处理线程数
        workerGroupSize: 20
        #    服务端bossGroup 的等待队列大小
        bossGroupQueueSize: 128
    zk:
      address: 192.168.73.131:2191,192.168.73.131:2192,192.168.73.131:2193
      openzk: true