server:
  port: 8082
simplerpc:
  netty:
    server:
      isrun: false
    client:
      #  netty连接地址
      address: {com.hu.api.IUserService: 127.0.0.1:9091&127.0.0.1:9092,com.hu.api.OrderService: 127.0.0.1:9091}
      connecttimeout: 3000
      loadbalancing: response_time
      threadpoll:
        threadSize: 10
    zk:
      address: 139.196.79.22:2181
      openzk: true




